theme: jekyll-theme-minimal
title: What's Up Compadres To Ian Flanders's Page
description: Bookmark the page to see what happens. Follow my Soundcloud, link is on the site.
link: https://soundcloud.com/user-73419152
